server.port=8081
spring.application.name=irk-Backend

# Dane logowania do Dockera
spring.datasource.url=jdbc:postgresql://localhost:5432/irk_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Ustawienie Hibernate, ?eby sam zarz?dza? tabelami w bazie
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect